/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CommandRouteImport } from './routes/command'
import { Route as EndeavoursRouteImport } from './routes/endeavours'
import { Route as InboxRouteImport } from './routes/inbox'
import { Route as IntelligenceRouteImport } from './routes/intelligence'
import { Route as InterfacesRouteImport } from './routes/interfaces'
import { Route as PipelineRouteImport } from './routes/pipeline'
import { Route as ProspectsRouteImport } from './routes/prospects'
import { Route as ResearchRouteImport } from './routes/research'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as EndeavoursIndexRouteImport } from './routes/endeavours.index'
import { Route as EndeavoursIdRouteImport } from './routes/endeavours.$id'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CommandRoute = CommandRouteImport.update({
  id: '/command',
  path: '/command',
  getParentRoute: () => rootRouteImport,
} as any)
const EndeavoursRoute = EndeavoursRouteImport.update({
  id: '/endeavours',
  path: '/endeavours',
  getParentRoute: () => rootRouteImport,
} as any)
const InboxRoute = InboxRouteImport.update({
  id: '/inbox',
  path: '/inbox',
  getParentRoute: () => rootRouteImport,
} as any)
const IntelligenceRoute = IntelligenceRouteImport.update({
  id: '/intelligence',
  path: '/intelligence',
  getParentRoute: () => rootRouteImport,
} as any)
const InterfacesRoute = InterfacesRouteImport.update({
  id: '/interfaces',
  path: '/interfaces',
  getParentRoute: () => rootRouteImport,
} as any)
const PipelineRoute = PipelineRouteImport.update({
  id: '/pipeline',
  path: '/pipeline',
  getParentRoute: () => rootRouteImport,
} as any)
const ProspectsRoute = ProspectsRouteImport.update({
  id: '/prospects',
  path: '/prospects',
  getParentRoute: () => rootRouteImport,
} as any)
const ResearchRoute = ResearchRouteImport.update({
  id: '/research',
  path: '/research',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const EndeavoursIndexRoute = EndeavoursIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => EndeavoursRoute,
} as any)
const EndeavoursIdRoute = EndeavoursIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => EndeavoursRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/command': typeof CommandRoute
  '/endeavours': typeof EndeavoursRouteWithChildren
  '/inbox': typeof InboxRoute
  '/intelligence': typeof IntelligenceRoute
  '/interfaces': typeof InterfacesRoute
  '/pipeline': typeof PipelineRoute
  '/prospects': typeof ProspectsRoute
  '/research': typeof ResearchRoute
  '/settings': typeof SettingsRoute
  '/endeavours/$id': typeof EndeavoursIdRoute
  '/endeavours/': typeof EndeavoursIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/command': typeof CommandRoute
  '/inbox': typeof InboxRoute
  '/intelligence': typeof IntelligenceRoute
  '/interfaces': typeof InterfacesRoute
  '/pipeline': typeof PipelineRoute
  '/prospects': typeof ProspectsRoute
  '/research': typeof ResearchRoute
  '/settings': typeof SettingsRoute
  '/endeavours/$id': typeof EndeavoursIdRoute
  '/endeavours': typeof EndeavoursIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/command': typeof CommandRoute
  '/endeavours': typeof EndeavoursRouteWithChildren
  '/inbox': typeof InboxRoute
  '/intelligence': typeof IntelligenceRoute
  '/interfaces': typeof InterfacesRoute
  '/pipeline': typeof PipelineRoute
  '/prospects': typeof ProspectsRoute
  '/research': typeof ResearchRoute
  '/settings': typeof SettingsRoute
  '/endeavours/$id': typeof EndeavoursIdRoute
  '/endeavours/': typeof EndeavoursIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/command'
    | '/endeavours'
    | '/inbox'
    | '/intelligence'
    | '/interfaces'
    | '/pipeline'
    | '/prospects'
    | '/research'
    | '/settings'
    | '/endeavours/$id'
    | '/endeavours/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/command'
    | '/inbox'
    | '/intelligence'
    | '/interfaces'
    | '/pipeline'
    | '/prospects'
    | '/research'
    | '/settings'
    | '/endeavours/$id'
    | '/endeavours'
  id:
    | '__root__'
    | '/'
    | '/command'
    | '/endeavours'
    | '/inbox'
    | '/intelligence'
    | '/interfaces'
    | '/pipeline'
    | '/prospects'
    | '/research'
    | '/settings'
    | '/endeavours/$id'
    | '/endeavours/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CommandRoute: typeof CommandRoute
  EndeavoursRoute: typeof EndeavoursRouteWithChildren
  InboxRoute: typeof InboxRoute
  IntelligenceRoute: typeof IntelligenceRoute
  InterfacesRoute: typeof InterfacesRoute
  PipelineRoute: typeof PipelineRoute
  ProspectsRoute: typeof ProspectsRoute
  ResearchRoute: typeof ResearchRoute
  SettingsRoute: typeof SettingsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/command': {
      id: '/command'
      path: '/command'
      fullPath: '/command'
      preLoaderRoute: typeof CommandRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/endeavours': {
      id: '/endeavours'
      path: '/endeavours'
      fullPath: '/endeavours'
      preLoaderRoute: typeof EndeavoursRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/inbox': {
      id: '/inbox'
      path: '/inbox'
      fullPath: '/inbox'
      preLoaderRoute: typeof InboxRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/intelligence': {
      id: '/intelligence'
      path: '/intelligence'
      fullPath: '/intelligence'
      preLoaderRoute: typeof IntelligenceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/interfaces': {
      id: '/interfaces'
      path: '/interfaces'
      fullPath: '/interfaces'
      preLoaderRoute: typeof InterfacesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pipeline': {
      id: '/pipeline'
      path: '/pipeline'
      fullPath: '/pipeline'
      preLoaderRoute: typeof PipelineRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/prospects': {
      id: '/prospects'
      path: '/prospects'
      fullPath: '/prospects'
      preLoaderRoute: typeof ProspectsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/research': {
      id: '/research'
      path: '/research'
      fullPath: '/research'
      preLoaderRoute: typeof ResearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/endeavours/': {
      id: '/endeavours/'
      path: '/'
      fullPath: '/endeavours/'
      preLoaderRoute: typeof EndeavoursIndexRouteImport
      parentRoute: typeof EndeavoursRoute
    }
    '/endeavours/$id': {
      id: '/endeavours/$id'
      path: '/$id'
      fullPath: '/endeavours/$id'
      preLoaderRoute: typeof EndeavoursIdRouteImport
      parentRoute: typeof EndeavoursRoute
    }
  }
}

interface EndeavoursRouteChildren {
  EndeavoursIdRoute: typeof EndeavoursIdRoute
  EndeavoursIndexRoute: typeof EndeavoursIndexRoute
}

const EndeavoursRouteChildren: EndeavoursRouteChildren = {
  EndeavoursIdRoute: EndeavoursIdRoute,
  EndeavoursIndexRoute: EndeavoursIndexRoute,
}

const EndeavoursRouteWithChildren = EndeavoursRoute._addFileChildren(
  EndeavoursRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CommandRoute: CommandRoute,
  EndeavoursRoute: EndeavoursRouteWithChildren,
  InboxRoute: InboxRoute,
  IntelligenceRoute: IntelligenceRoute,
  InterfacesRoute: InterfacesRoute,
  PipelineRoute: PipelineRoute,
  ProspectsRoute: ProspectsRoute,
  ResearchRoute: ResearchRoute,
  SettingsRoute: SettingsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
