/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CommandRouteImport } from './routes/command'
import { Route as EndeavoursRouteImport } from './routes/endeavours'
import { Route as InboxRouteImport } from './routes/inbox'
import { Route as IntelligenceRouteImport } from './routes/intelligence'
import { Route as InterfacesRouteImport } from './routes/interfaces'
import { Route as LoginRouteImport } from './routes/login'
import { Route as PipelineRouteImport } from './routes/pipeline'
import { Route as ProspectsRouteImport } from './routes/prospects'
import { Route as ResearchRouteImport } from './routes/research'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as AuthGoogleRouteImport } from './routes/auth.google'
import { Route as AuthLogoutRouteImport } from './routes/auth.logout'
import { Route as AuthTestLoginRouteImport } from './routes/auth.test-login'
import { Route as EndeavoursIndexRouteImport } from './routes/endeavours.index'
import { Route as EndeavoursIdRouteImport } from './routes/endeavours.$id'
import { Route as AuthGoogleCallbackRouteImport } from './routes/auth.google.callback'
import { Route as MailboxesGoogleCallbackRouteImport } from './routes/mailboxes.google.callback'
import { Route as MailboxesGoogleConnectRouteImport } from './routes/mailboxes.google.connect'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CommandRoute = CommandRouteImport.update({
  id: '/command',
  path: '/command',
  getParentRoute: () => rootRouteImport,
} as any)
const EndeavoursRoute = EndeavoursRouteImport.update({
  id: '/endeavours',
  path: '/endeavours',
  getParentRoute: () => rootRouteImport,
} as any)
const InboxRoute = InboxRouteImport.update({
  id: '/inbox',
  path: '/inbox',
  getParentRoute: () => rootRouteImport,
} as any)
const IntelligenceRoute = IntelligenceRouteImport.update({
  id: '/intelligence',
  path: '/intelligence',
  getParentRoute: () => rootRouteImport,
} as any)
const InterfacesRoute = InterfacesRouteImport.update({
  id: '/interfaces',
  path: '/interfaces',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const PipelineRoute = PipelineRouteImport.update({
  id: '/pipeline',
  path: '/pipeline',
  getParentRoute: () => rootRouteImport,
} as any)
const ProspectsRoute = ProspectsRouteImport.update({
  id: '/prospects',
  path: '/prospects',
  getParentRoute: () => rootRouteImport,
} as any)
const ResearchRoute = ResearchRouteImport.update({
  id: '/research',
  path: '/research',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthGoogleRoute = AuthGoogleRouteImport.update({
  id: '/auth/google',
  path: '/auth/google',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthLogoutRoute = AuthLogoutRouteImport.update({
  id: '/auth/logout',
  path: '/auth/logout',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthTestLoginRoute = AuthTestLoginRouteImport.update({
  id: '/auth/test-login',
  path: '/auth/test-login',
  getParentRoute: () => rootRouteImport,
} as any)
const EndeavoursIndexRoute = EndeavoursIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => EndeavoursRoute,
} as any)
const EndeavoursIdRoute = EndeavoursIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => EndeavoursRoute,
} as any)
const AuthGoogleCallbackRoute = AuthGoogleCallbackRouteImport.update({
  id: '/callback',
  path: '/callback',
  getParentRoute: () => AuthGoogleRoute,
} as any)
const MailboxesGoogleCallbackRoute = MailboxesGoogleCallbackRouteImport.update({
  id: '/mailboxes/google/callback',
  path: '/mailboxes/google/callback',
  getParentRoute: () => rootRouteImport,
} as any)
const MailboxesGoogleConnectRoute = MailboxesGoogleConnectRouteImport.update({
  id: '/mailboxes/google/connect',
  path: '/mailboxes/google/connect',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/command': typeof CommandRoute
  '/endeavours': typeof EndeavoursRouteWithChildren
  '/inbox': typeof InboxRoute
  '/intelligence': typeof IntelligenceRoute
  '/interfaces': typeof InterfacesRoute
  '/login': typeof LoginRoute
  '/pipeline': typeof PipelineRoute
  '/prospects': typeof ProspectsRoute
  '/research': typeof ResearchRoute
  '/settings': typeof SettingsRoute
  '/auth/google': typeof AuthGoogleRouteWithChildren
  '/auth/logout': typeof AuthLogoutRoute
  '/auth/test-login': typeof AuthTestLoginRoute
  '/endeavours/$id': typeof EndeavoursIdRoute
  '/endeavours/': typeof EndeavoursIndexRoute
  '/auth/google/callback': typeof AuthGoogleCallbackRoute
  '/mailboxes/google/callback': typeof MailboxesGoogleCallbackRoute
  '/mailboxes/google/connect': typeof MailboxesGoogleConnectRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/command': typeof CommandRoute
  '/inbox': typeof InboxRoute
  '/intelligence': typeof IntelligenceRoute
  '/interfaces': typeof InterfacesRoute
  '/login': typeof LoginRoute
  '/pipeline': typeof PipelineRoute
  '/prospects': typeof ProspectsRoute
  '/research': typeof ResearchRoute
  '/settings': typeof SettingsRoute
  '/auth/google': typeof AuthGoogleRouteWithChildren
  '/auth/logout': typeof AuthLogoutRoute
  '/auth/test-login': typeof AuthTestLoginRoute
  '/endeavours/$id': typeof EndeavoursIdRoute
  '/endeavours': typeof EndeavoursIndexRoute
  '/auth/google/callback': typeof AuthGoogleCallbackRoute
  '/mailboxes/google/callback': typeof MailboxesGoogleCallbackRoute
  '/mailboxes/google/connect': typeof MailboxesGoogleConnectRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/command': typeof CommandRoute
  '/endeavours': typeof EndeavoursRouteWithChildren
  '/inbox': typeof InboxRoute
  '/intelligence': typeof IntelligenceRoute
  '/interfaces': typeof InterfacesRoute
  '/login': typeof LoginRoute
  '/pipeline': typeof PipelineRoute
  '/prospects': typeof ProspectsRoute
  '/research': typeof ResearchRoute
  '/settings': typeof SettingsRoute
  '/auth/google': typeof AuthGoogleRouteWithChildren
  '/auth/logout': typeof AuthLogoutRoute
  '/auth/test-login': typeof AuthTestLoginRoute
  '/endeavours/$id': typeof EndeavoursIdRoute
  '/endeavours/': typeof EndeavoursIndexRoute
  '/auth/google/callback': typeof AuthGoogleCallbackRoute
  '/mailboxes/google/callback': typeof MailboxesGoogleCallbackRoute
  '/mailboxes/google/connect': typeof MailboxesGoogleConnectRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/command'
    | '/endeavours'
    | '/inbox'
    | '/intelligence'
    | '/interfaces'
    | '/login'
    | '/pipeline'
    | '/prospects'
    | '/research'
    | '/settings'
    | '/auth/google'
    | '/auth/logout'
    | '/auth/test-login'
    | '/endeavours/$id'
    | '/endeavours/'
    | '/auth/google/callback'
    | '/mailboxes/google/callback'
    | '/mailboxes/google/connect'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/command'
    | '/inbox'
    | '/intelligence'
    | '/interfaces'
    | '/login'
    | '/pipeline'
    | '/prospects'
    | '/research'
    | '/settings'
    | '/auth/google'
    | '/auth/logout'
    | '/auth/test-login'
    | '/endeavours/$id'
    | '/endeavours'
    | '/auth/google/callback'
    | '/mailboxes/google/callback'
    | '/mailboxes/google/connect'
  id:
    | '__root__'
    | '/'
    | '/command'
    | '/endeavours'
    | '/inbox'
    | '/intelligence'
    | '/interfaces'
    | '/login'
    | '/pipeline'
    | '/prospects'
    | '/research'
    | '/settings'
    | '/auth/google'
    | '/auth/logout'
    | '/auth/test-login'
    | '/endeavours/$id'
    | '/endeavours/'
    | '/auth/google/callback'
    | '/mailboxes/google/callback'
    | '/mailboxes/google/connect'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CommandRoute: typeof CommandRoute
  EndeavoursRoute: typeof EndeavoursRouteWithChildren
  InboxRoute: typeof InboxRoute
  IntelligenceRoute: typeof IntelligenceRoute
  InterfacesRoute: typeof InterfacesRoute
  LoginRoute: typeof LoginRoute
  PipelineRoute: typeof PipelineRoute
  ProspectsRoute: typeof ProspectsRoute
  ResearchRoute: typeof ResearchRoute
  SettingsRoute: typeof SettingsRoute
  AuthGoogleRoute: typeof AuthGoogleRouteWithChildren
  AuthLogoutRoute: typeof AuthLogoutRoute
  AuthTestLoginRoute: typeof AuthTestLoginRoute
  MailboxesGoogleCallbackRoute: typeof MailboxesGoogleCallbackRoute
  MailboxesGoogleConnectRoute: typeof MailboxesGoogleConnectRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/command': {
      id: '/command'
      path: '/command'
      fullPath: '/command'
      preLoaderRoute: typeof CommandRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/endeavours': {
      id: '/endeavours'
      path: '/endeavours'
      fullPath: '/endeavours'
      preLoaderRoute: typeof EndeavoursRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/inbox': {
      id: '/inbox'
      path: '/inbox'
      fullPath: '/inbox'
      preLoaderRoute: typeof InboxRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/intelligence': {
      id: '/intelligence'
      path: '/intelligence'
      fullPath: '/intelligence'
      preLoaderRoute: typeof IntelligenceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/interfaces': {
      id: '/interfaces'
      path: '/interfaces'
      fullPath: '/interfaces'
      preLoaderRoute: typeof InterfacesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pipeline': {
      id: '/pipeline'
      path: '/pipeline'
      fullPath: '/pipeline'
      preLoaderRoute: typeof PipelineRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/prospects': {
      id: '/prospects'
      path: '/prospects'
      fullPath: '/prospects'
      preLoaderRoute: typeof ProspectsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/research': {
      id: '/research'
      path: '/research'
      fullPath: '/research'
      preLoaderRoute: typeof ResearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/google': {
      id: '/auth/google'
      path: '/auth/google'
      fullPath: '/auth/google'
      preLoaderRoute: typeof AuthGoogleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/logout': {
      id: '/auth/logout'
      path: '/auth/logout'
      fullPath: '/auth/logout'
      preLoaderRoute: typeof AuthLogoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/test-login': {
      id: '/auth/test-login'
      path: '/auth/test-login'
      fullPath: '/auth/test-login'
      preLoaderRoute: typeof AuthTestLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/endeavours/': {
      id: '/endeavours/'
      path: '/'
      fullPath: '/endeavours/'
      preLoaderRoute: typeof EndeavoursIndexRouteImport
      parentRoute: typeof EndeavoursRoute
    }
    '/endeavours/$id': {
      id: '/endeavours/$id'
      path: '/$id'
      fullPath: '/endeavours/$id'
      preLoaderRoute: typeof EndeavoursIdRouteImport
      parentRoute: typeof EndeavoursRoute
    }
    '/auth/google/callback': {
      id: '/auth/google/callback'
      path: '/callback'
      fullPath: '/auth/google/callback'
      preLoaderRoute: typeof AuthGoogleCallbackRouteImport
      parentRoute: typeof AuthGoogleRoute
    }
    '/mailboxes/google/callback': {
      id: '/mailboxes/google/callback'
      path: '/mailboxes/google/callback'
      fullPath: '/mailboxes/google/callback'
      preLoaderRoute: typeof MailboxesGoogleCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mailboxes/google/connect': {
      id: '/mailboxes/google/connect'
      path: '/mailboxes/google/connect'
      fullPath: '/mailboxes/google/connect'
      preLoaderRoute: typeof MailboxesGoogleConnectRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface EndeavoursRouteChildren {
  EndeavoursIdRoute: typeof EndeavoursIdRoute
  EndeavoursIndexRoute: typeof EndeavoursIndexRoute
}

const EndeavoursRouteChildren: EndeavoursRouteChildren = {
  EndeavoursIdRoute: EndeavoursIdRoute,
  EndeavoursIndexRoute: EndeavoursIndexRoute,
}

const EndeavoursRouteWithChildren = EndeavoursRoute._addFileChildren(
  EndeavoursRouteChildren,
)

interface AuthGoogleRouteChildren {
  AuthGoogleCallbackRoute: typeof AuthGoogleCallbackRoute
}

const AuthGoogleRouteChildren: AuthGoogleRouteChildren = {
  AuthGoogleCallbackRoute: AuthGoogleCallbackRoute,
}

const AuthGoogleRouteWithChildren = AuthGoogleRoute._addFileChildren(
  AuthGoogleRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CommandRoute: CommandRoute,
  EndeavoursRoute: EndeavoursRouteWithChildren,
  InboxRoute: InboxRoute,
  IntelligenceRoute: IntelligenceRoute,
  InterfacesRoute: InterfacesRoute,
  LoginRoute: LoginRoute,
  PipelineRoute: PipelineRoute,
  ProspectsRoute: ProspectsRoute,
  ResearchRoute: ResearchRoute,
  SettingsRoute: SettingsRoute,
  AuthGoogleRoute: AuthGoogleRouteWithChildren,
  AuthLogoutRoute: AuthLogoutRoute,
  AuthTestLoginRoute: AuthTestLoginRoute,
  MailboxesGoogleCallbackRoute: MailboxesGoogleCallbackRoute,
  MailboxesGoogleConnectRoute: MailboxesGoogleConnectRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
